pipeline:
  publish:
    image: plugins/docker
    repo: minuntu/nvidia-bminer
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
